version: '3.7'

services:
  aurora-local:
    image: 'postgres:10.14' # current Aurora Serverless postgres DB version, do not change
    command: ['postgres',
              '-c', 'log_line_prefix=%m [%p/%l] [%u:%a] ',
              '-c', 'log_min_messages=INFO',
              '-c', 'log_statement=all',
              '-c', 'log_connections=true',
    ]
    environment:
      POSTGRES_USER: 'master'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'github'
    volumes:
      - udexp-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"

volumes:
  udexp-data:
    driver: local
